# This file was generated by GoReleaser. DO NOT EDIT.
cask "duty" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "505425db4344708d03c81044b2058eec6e3e7dc1c3aa8a2f0ab60d6997ee0e54"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f59f65b21a779f797cd3481ea884f46f9a8de8f755a3f23911d5514a539c8d5"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae54a4980fd413f5ca0015496fd02dd758af40c960a9fced18a7fbcb467b97f3"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd727d163a2e08732f3456dce1b5dac2f02a14a2d8809481fe0af134dae30330"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "duty"
  desc "File-based task system: markdown tasks, nested board indexes, one Go binary (CLI + TUI)"
  homepage "https://github.com/raphaelCamblong/duty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duty"
  bash_completion "completions/duty.bash"
  fish_completion "completions/duty.fish"
  zsh_completion "completions/duty.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duty"]
    end
  end

  # No zap stanza required

end
