# This file was generated by GoReleaser. DO NOT EDIT.
cask "duty" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "83cb60d62b0ef8bf6e81cc6aae9459020d128f63cea4188f3822d63467333774"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbb207604a6e59a5ae77e2a876be38170ad29d0ce9878f9f9a04e7c8408216ee"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56f73b7cd99ad16b5ea46f77074e56a9441ef095e35e8c0fc7c442ce1a2599fd"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "954974e665d8d34e005283137f8bd23bfb49575d5e052bb77af45f2ded05ccdc"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "duty"
  desc "File-based task system: markdown tasks, nested board indexes, one Go binary (CLI + TUI)"
  homepage "https://github.com/raphaelCamblong/duty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duty"
  bash_completion "completions/duty.bash"
  fish_completion "completions/duty.fish"
  zsh_completion "completions/duty.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duty"]
    end
  end

  # No zap stanza required

end
