# This file was generated by GoReleaser. DO NOT EDIT.
cask "duty" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "65375fa4dfc9ce66b9dbe5df9635fe5d307fca7ff4c8a8cca4f981a10af28bfd"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a20aa259ccb925fa08a637df6864de631d475d63b9fbe8f594db5b5b98fec00e"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d988d5675056ea936a9d2fd1429bec19da8e49558b908dad4c4f587dabf395f8"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6c8eb738090c7e0ebce6ea3b2de0fcebe65e4f0a3d536850651e3bfcc0fe3f8"
      url "https://github.com/raphaelCamblong/duty/releases/download/v#{version}/duty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "duty"
  desc "File-based task system: markdown tasks, nested board indexes, one Go binary (CLI + TUI)"
  homepage "https://github.com/raphaelCamblong/duty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "duty"
  bash_completion "completions/duty.bash"
  fish_completion "completions/duty.fish"
  zsh_completion "completions/duty.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/duty"]
    end
  end

  # No zap stanza required

end
